version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-task-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf
      MYSQL_DATABASE: task-management-system
      MYSQL_USER: emara
      MYSQL_PASSWORD: asdfasdf
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis-task-db
    restart: always
    ports:
      - "6378:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  rabbitmq_data:
